### ISSUE TITLE
abbr not supported in markdown

### ISSUE THREAD

**Issue by oupala** [mudassir0909/jsonresume-theme-elegant#73] opened 2016-04-15 14:16 UTC
markdown has been recently added as a new feature of this theme, it works well and is a pleasure to use.

Unfortunately, the markdown parser does not support the abbr, which identified as a bug in marked: chjj/marked#27

The issue suggest to use another markdown parser known as markdown-it: [markdown-it](https://github.com/markdown-it/markdown-it).

I let you decide what to do.

**Comment by mudassir0909** [comment] 2016-04-16 17:03
oh, I didn't know about this, my reply would be same as [here](https://github.com/mudassir0909/jsonresume-theme-elegant/issues/74#issuecomment-210857992) :)

**Comment by oupala** [comment] 2016-05-04 10:55
@mudassir0909 it seems that you closed the issue a bit too fast!

I tried to use abbr, but I did not succeeded due to some limitations. Let me explain them.

**Comment by mudassir0909** [comment] 2016-05-04 13:11
Well, I tested it with the following string & it worked perfectly.

```json
        "*[HTML]: Hyper Text Markup Language.\nThe HTML specification is maintained by the W3C."
```

Added the above string inside the `highlights` array & it worked as expected

**Comment by mudassir0909** [comment] 2016-05-04 13:13
And yes, each string is parsed separately because there is no other way to globally compile everything & put them back into where they came from. For example, `work[0].highlights` is an array, you can't just compile the entire array, you have to individually compile each item in the array unless you have any other idea for the same

**Comment by oupala** [comment] 2016-05-18 16:08
I tried with the exact same string as you:

```md
 "*[HTML]: Hyper Text Markup Language.\nThe HTML specification is maintained by the W3C."
```

and I get the following generated html:

```html
<li class="mop-wrapper">
    <p>@@@@~*[HTML]: Hyper Text Markup Language.
        <br>The HTML specification is maintained by the W3C.~@@@@</p>
</li>
```

Of course, the `abbr` is not displayed.

When I use this string:

```md
"this is HTML !\n*[HTML]: Hyper Text Markup Language\n"
```

and I get the following generated html:

```html
<li class="mop-wrapper">
    <p>@@@@~this is <abbr title="Hyper Text Markup Language">HTML</abbr> !</p>
    <p>~@@@@</p>
</li>

This time, the `abbr` is not displayed, but there is still some strange strings: `@@@@~`.

**Comment by mudassir0909** [comment] 2016-05-19 08:29
strange! let me check this weekend

**Comment by oupala** [comment] 2016-06-22 15:19
Hi @mudassir0909, did you had time to test it?

**Comment by mudassir0909** [comment] 2016-06-22 17:31
Yes I did test it & this is what I'm seeing

<img width="528" alt="screen shot 2016-06-22 at 10 59 05 pm" src="https://cloud.githubusercontent.com/assets/1861842/16276685/1327f366-38cd-11e6-870a-bf5093b95176.png">

for the json

<img width="812" alt="screen shot 2016-06-22 at 11 00 25 pm" src="https://cloud.githubusercontent.com/assets/1861842/16276703/2171a2e6-38cd-11e6-8180-6b638c7ddb9a.png">

Maybe you could share your jsonresume profile? that'd be more helpful

**Comment by oupala** [comment] 2016-07-04 08:45
I tried with the markdown that you copied:

```markdown
      "summary": "conception and QA",
      "highlights": [
        "this is HTML !\n*[HTML]: Hyper Text Markup Language\n",
        "conception of a distributed system"
```

And the result is showing some annoying `@@@@~` and `~@@@@` strings:

![screenshot 2016-07-04 10 40 10](https://cloud.githubusercontent.com/assets/13458743/16555312/637f635c-41d4-11e6-83c1-4afed9f300c1.png)

I don't have any idea on where it could come from. I'm using debian jessie with a standard nvm install of npm.

**Comment by oupala** [comment] 2016-07-04 08:52
Further testing shows me that the strange strings are due to the final `\n`.

Without the final `\n`, the abbr is not rendered, but the `@@@@~` disappear.

**Comment by mudassir0909** [comment] 2016-07-04 10:48
Ah! Maybe compatibility issue with the OS, if you have a VM, can you try publishing the same from ubuntu & see if the issue still persists?

Also, if possible open up node console & include `mardown-it`, `markdown-it-abbr`. Try to convert the markdown in the console & if the issue is at package level, maybe we can raise the issue in their github repository

**Comment by oupala** [comment] 2016-07-05 15:03
The problem does not come from debian: I've just tested with Ubuntu Xenial (a real Ubuntu, not a VM) and I get the same result. What OS are you using?

Where does that come from?

I thought it could come from the encoding:

```bash
$ file resume.json 
resume.json: UTF-8 Unicode text, with very long lines
```

What is your encoding?

**Comment by oupala** [comment] 2016-07-05 15:40
Could you help me test `markdown-it` and `markdown-it-abbr` from the node console? I would like to test if only I knew how to do it.

**Comment by mudassir0909** [comment] 2016-07-10 16:09
Assume you have node installed on your machine, you can open node console using the following command

```
node
```

Once you enter the console you could do

```
var markdown = require('markdown-it')({
    breaks: true
}).use(require('markdown-it-abbr'));

markdown.render("this is HTML !\n*[HTML]: Hyper Text Markup Language\n")
```

See if the output exports special characters

*P.S.* Ensure you have `markdown-it` & `markdown-it-abbr` installed globally

**Comment by mudassir0909** [comment] 2016-07-10 16:10
By the here is my encoding

```
$ file resume.json
resume.json: ASCII English text
```

**Comment by mudassir0909** [comment] 2016-07-10 16:11
Also, did you publish your resume somewhere? can I have a look at it?

**Comment by oupala** [comment] 2016-07-11 15:43
Here is the result of my test:

```bash
>node
> var markdown = require('markdown-it')({
...     breaks: true
... }).use(require('markdown-it-abbr'));
undefined
> markdown.render("this is HTML !\n*[HTML]: Hyper Text Markup Language\n")
'<p>this is <abbr title="Hyper Text Markup Language">HTML</abbr> !</p>\n'
> .exit
```

As my file is in UTF-8 and yours is in ASCII, this could explain the different behaviour. Could please add an "é" character somewhere in your resume, save it in UTF-8, and try to render it again?

My resume is not published anywhere at this time (it is not finished yet as there is still some bugs), but I can send it to by private mail.

**Comment by mudassir0909** [comment] 2016-07-12 09:17
shoot me an email at **mudassir.dev @ gmail.com**, attach your resume.json file, it'll make things easier for me

**Comment by oupala** [comment] 2016-08-19 11:18
It might be due to my locales.

Here are mines:

```bash
>locale
LANG=fr_FR.utf8
LANGUAGE=
LC_CTYPE="fr_FR.utf8"
LC_NUMERIC="fr_FR.utf8"
LC_TIME="fr_FR.utf8"
LC_COLLATE="fr_FR.utf8"
LC_MONETARY="fr_FR.utf8"
LC_MESSAGES="fr_FR.utf8"
LC_PAPER="fr_FR.utf8"
LC_NAME="fr_FR.utf8"
LC_ADDRESS="fr_FR.utf8"
LC_TELEPHONE="fr_FR.utf8"
LC_MEASUREMENT="fr_FR.utf8"
LC_IDENTIFICATION="fr_FR.utf8"
LC_ALL=
```

What are yours?

**Comment by mudassir0909** [comment] 2016-08-19 13:25
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

**Comment by mudassir0909** [comment] 2016-08-19 13:26
And even then this issue is probably related to `markdown-it-abbr` npm package & has nothing to with this them, I feel

**Comment by oupala** [comment] 2016-08-19 13:42
As explained in my [previous comment](https://github.com/mudassir0909/jsonresume-theme-elegant/issues/73#issuecomment-231774540), everything seems to work very well with `markdown-it` and `markdown-it-abbr`.

Do you really think I should try to have a deeper look at `markdown-it-abbr`?

**Comment by mudassir0909** [comment] 2016-08-20 07:56
As mentioned in the email, it could be due to hackmyresume. If you are not having any issues when you host your resume(jsonresume) locally then it's probably hackmyresume

See https://github.com/mudassir0909/jsonresume-theme-elegant#contributing on how to host your resume locally

**Comment by oupala** [comment] 2016-08-23 14:23
It works very well with `jsonresume-theme-elegant` self-hosted. But how do you manage to do that without `json-server`?

I'll have to dive into `hackmyresume` to find out where it does come from...

Thanks a lot for your patience!

**Comment by mudassir0909** [comment] 2016-08-23 18:55
no problem :) closing the issue then

**Comment by mudassir0909** [comment] 2016-08-23 18:55
>  how do you manage to do that without json-server?

I didn't get this part

**Closed by mudassir0909** 2016-08-23 18:55 UTC

**Comment by oupala** [comment] 2016-08-24 09:33
I edited the [previous comment](/mudassir0909/jsonresume-theme-elegant/issues/73#issuecomment-241747665).

How do you manage to render the resume without `resume-cli`?

**Comment by mudassir0909** [comment] 2016-08-24 09:35
Aha, this even I've no clue, although this might help 

https://github.com/mudassir0909/jsonresume-theme-elegant/blob/master/serve.js#L47

We use this script to render the theme locally, you could do the similar thing

**Comment by oupala** [comment] 2016-08-24 12:49
So... What is `resume-cli` for if `jsonresume-theme-elegant` is a standalone tool?
